spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 실행시점에 기존 데이터 초기화 후 자동으로 table을 만들어 주는 설정
    properties:
      hibernate:
        #show_sql: true  # system.out으로 sql을 확인할 수 있는 설정
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug # hibernate SQL 로그를 디버그 모드로 사용 -> hibernate가 생성하는 sql을 로그로 확인할 수 있는 설정
